---
# tasks file for while_true_do.srv_nfs

- name: Manage nfs Packages
  package:
    name: "{{ wtd_srv_nfs_package }}"
    state: "{{ wtd_srv_nfs_package_state }}"
  become: true
  tags:
    - nfs
    - package
