---
- name: Manage nfs exports Folder
  file:
    path: "{{ item.path }}"
    state: "directory"
    owner: "{{ item.owner|default('nobody') }}"
    group: "{{ item.group|default('nobody') }}"
    mode: "{{ item.mode|default('0750') }}"
  become: true
  tags:
    - nfs
    - directory

- name: Manage nfs exports Configuration
  template:
    src: "exports_d.j2"
    dest: "/etc/exports.d/{{ item.name }}.exports"
  become: true
  when:
    - item.hosts is defined
  tags:
    - nfs
    - configuration
