---
- name: Converge
  hosts: all
  roles:
    - role: while_true_do.srv_nfs
      wtd_srv_nfs_conf_exports:
        - name: "testshare"
          path: "/testshare"
          owner: "nobody"
          group: "nobody"
          mode: "0750"
          hosts:
            - host: "192.168.0.1"
              option: "rw,sync"
            - host: "192.168.10.0/24"
